// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PrivateDealsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PrivateDealsV3Api}
 */
public final class PrivateDealsV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PrivateDealsV3Api)
    PrivateDealsV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PrivateDealsV3Api.class.getName());
  }
  // Use PrivateDealsV3Api.newBuilder() to construct.
  private PrivateDealsV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PrivateDealsV3Api() {
    price_ = "";
    quantity_ = "";
    amount_ = "";
    tradeId_ = "";
    clientOrderId_ = "";
    orderId_ = "";
    feeAmount_ = "";
    feeCurrency_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PrivateDealsV3ApiProto.internal_static_PrivateDealsV3Api_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PrivateDealsV3ApiProto.internal_static_PrivateDealsV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PrivateDealsV3Api.class, Builder.class);
  }

  public static final int PRICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object price_ = "";
  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  @Override
  public String getPrice() {
    Object ref = price_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  @Override
  public com.google.protobuf.ByteString
      getPriceBytes() {
    Object ref = price_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object quantity_ = "";
  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  @Override
  public String getQuantity() {
    Object ref = quantity_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      quantity_ = s;
      return s;
    }
  }
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  @Override
  public com.google.protobuf.ByteString
      getQuantityBytes() {
    Object ref = quantity_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      quantity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object amount_ = "";
  /**
   * <code>string amount = 3;</code>
   * @return The amount.
   */
  @Override
  public String getAmount() {
    Object ref = amount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      amount_ = s;
      return s;
    }
  }
  /**
   * <code>string amount = 3;</code>
   * @return The bytes for amount.
   */
  @Override
  public com.google.protobuf.ByteString
      getAmountBytes() {
    Object ref = amount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      amount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADETYPE_FIELD_NUMBER = 4;
  private int tradeType_ = 0;
  /**
   * <code>int32 tradeType = 4;</code>
   * @return The tradeType.
   */
  @Override
  public int getTradeType() {
    return tradeType_;
  }

  public static final int ISMAKER_FIELD_NUMBER = 5;
  private boolean isMaker_ = false;
  /**
   * <code>bool isMaker = 5;</code>
   * @return The isMaker.
   */
  @Override
  public boolean getIsMaker() {
    return isMaker_;
  }

  public static final int ISSELFTRADE_FIELD_NUMBER = 6;
  private boolean isSelfTrade_ = false;
  /**
   * <code>bool isSelfTrade = 6;</code>
   * @return The isSelfTrade.
   */
  @Override
  public boolean getIsSelfTrade() {
    return isSelfTrade_;
  }

  public static final int TRADEID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object tradeId_ = "";
  /**
   * <code>string tradeId = 7;</code>
   * @return The tradeId.
   */
  @Override
  public String getTradeId() {
    Object ref = tradeId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tradeId_ = s;
      return s;
    }
  }
  /**
   * <code>string tradeId = 7;</code>
   * @return The bytes for tradeId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTradeIdBytes() {
    Object ref = tradeId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tradeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTORDERID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object clientOrderId_ = "";
  /**
   * <code>string clientOrderId = 8;</code>
   * @return The clientOrderId.
   */
  @Override
  public String getClientOrderId() {
    Object ref = clientOrderId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clientOrderId_ = s;
      return s;
    }
  }
  /**
   * <code>string clientOrderId = 8;</code>
   * @return The bytes for clientOrderId.
   */
  @Override
  public com.google.protobuf.ByteString
      getClientOrderIdBytes() {
    Object ref = clientOrderId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile Object orderId_ = "";
  /**
   * <code>string orderId = 9;</code>
   * @return The orderId.
   */
  @Override
  public String getOrderId() {
    Object ref = orderId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <code>string orderId = 9;</code>
   * @return The bytes for orderId.
   */
  @Override
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    Object ref = orderId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEEAMOUNT_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile Object feeAmount_ = "";
  /**
   * <code>string feeAmount = 10;</code>
   * @return The feeAmount.
   */
  @Override
  public String getFeeAmount() {
    Object ref = feeAmount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      feeAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string feeAmount = 10;</code>
   * @return The bytes for feeAmount.
   */
  @Override
  public com.google.protobuf.ByteString
      getFeeAmountBytes() {
    Object ref = feeAmount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      feeAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEECURRENCY_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile Object feeCurrency_ = "";
  /**
   * <code>string feeCurrency = 11;</code>
   * @return The feeCurrency.
   */
  @Override
  public String getFeeCurrency() {
    Object ref = feeCurrency_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      feeCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>string feeCurrency = 11;</code>
   * @return The bytes for feeCurrency.
   */
  @Override
  public com.google.protobuf.ByteString
      getFeeCurrencyBytes() {
    Object ref = feeCurrency_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      feeCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 12;
  private long time_ = 0L;
  /**
   * <code>int64 time = 12;</code>
   * @return The time.
   */
  @Override
  public long getTime() {
    return time_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(amount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, amount_);
    }
    if (tradeType_ != 0) {
      output.writeInt32(4, tradeType_);
    }
    if (isMaker_ != false) {
      output.writeBool(5, isMaker_);
    }
    if (isSelfTrade_ != false) {
      output.writeBool(6, isSelfTrade_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tradeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, tradeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientOrderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, clientOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(feeAmount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, feeAmount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(feeCurrency_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, feeCurrency_);
    }
    if (time_ != 0L) {
      output.writeInt64(12, time_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(amount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, amount_);
    }
    if (tradeType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, tradeType_);
    }
    if (isMaker_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isMaker_);
    }
    if (isSelfTrade_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isSelfTrade_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tradeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, tradeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientOrderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, clientOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(feeAmount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, feeAmount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(feeCurrency_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, feeCurrency_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, time_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PrivateDealsV3Api)) {
      return super.equals(obj);
    }
    PrivateDealsV3Api other = (PrivateDealsV3Api) obj;

    if (!getPrice()
        .equals(other.getPrice())) return false;
    if (!getQuantity()
        .equals(other.getQuantity())) return false;
    if (!getAmount()
        .equals(other.getAmount())) return false;
    if (getTradeType()
        != other.getTradeType()) return false;
    if (getIsMaker()
        != other.getIsMaker()) return false;
    if (getIsSelfTrade()
        != other.getIsSelfTrade()) return false;
    if (!getTradeId()
        .equals(other.getTradeId())) return false;
    if (!getClientOrderId()
        .equals(other.getClientOrderId())) return false;
    if (!getOrderId()
        .equals(other.getOrderId())) return false;
    if (!getFeeAmount()
        .equals(other.getFeeAmount())) return false;
    if (!getFeeCurrency()
        .equals(other.getFeeCurrency())) return false;
    if (getTime()
        != other.getTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount().hashCode();
    hash = (37 * hash) + TRADETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTradeType();
    hash = (37 * hash) + ISMAKER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsMaker());
    hash = (37 * hash) + ISSELFTRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSelfTrade());
    hash = (37 * hash) + TRADEID_FIELD_NUMBER;
    hash = (53 * hash) + getTradeId().hashCode();
    hash = (37 * hash) + CLIENTORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getClientOrderId().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    hash = (37 * hash) + FEEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFeeAmount().hashCode();
    hash = (37 * hash) + FEECURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getFeeCurrency().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PrivateDealsV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PrivateDealsV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PrivateDealsV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PrivateDealsV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PrivateDealsV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PrivateDealsV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PrivateDealsV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PrivateDealsV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PrivateDealsV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PrivateDealsV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PrivateDealsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PrivateDealsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PrivateDealsV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PrivateDealsV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrivateDealsV3Api)
      PrivateDealsV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PrivateDealsV3ApiProto.internal_static_PrivateDealsV3Api_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PrivateDealsV3ApiProto.internal_static_PrivateDealsV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PrivateDealsV3Api.class, Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PrivateDealsV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      price_ = "";
      quantity_ = "";
      amount_ = "";
      tradeType_ = 0;
      isMaker_ = false;
      isSelfTrade_ = false;
      tradeId_ = "";
      clientOrderId_ = "";
      orderId_ = "";
      feeAmount_ = "";
      feeCurrency_ = "";
      time_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PrivateDealsV3ApiProto.internal_static_PrivateDealsV3Api_descriptor;
    }

    @Override
    public PrivateDealsV3Api getDefaultInstanceForType() {
      return PrivateDealsV3Api.getDefaultInstance();
    }

    @Override
    public PrivateDealsV3Api build() {
      PrivateDealsV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PrivateDealsV3Api buildPartial() {
      PrivateDealsV3Api result = new PrivateDealsV3Api(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(PrivateDealsV3Api result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tradeType_ = tradeType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isMaker_ = isMaker_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isSelfTrade_ = isSelfTrade_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.tradeId_ = tradeId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.clientOrderId_ = clientOrderId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.orderId_ = orderId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.feeAmount_ = feeAmount_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.feeCurrency_ = feeCurrency_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.time_ = time_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PrivateDealsV3Api) {
        return mergeFrom((PrivateDealsV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PrivateDealsV3Api other) {
      if (other == PrivateDealsV3Api.getDefaultInstance()) return this;
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getQuantity().isEmpty()) {
        quantity_ = other.quantity_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAmount().isEmpty()) {
        amount_ = other.amount_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getTradeType() != 0) {
        setTradeType(other.getTradeType());
      }
      if (other.getIsMaker() != false) {
        setIsMaker(other.getIsMaker());
      }
      if (other.getIsSelfTrade() != false) {
        setIsSelfTrade(other.getIsSelfTrade());
      }
      if (!other.getTradeId().isEmpty()) {
        tradeId_ = other.tradeId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getClientOrderId().isEmpty()) {
        clientOrderId_ = other.clientOrderId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getFeeAmount().isEmpty()) {
        feeAmount_ = other.feeAmount_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getFeeCurrency().isEmpty()) {
        feeCurrency_ = other.feeCurrency_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              price_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              quantity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              amount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              tradeType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              isMaker_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              isSelfTrade_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              tradeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              clientOrderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              orderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              feeAmount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              feeCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              time_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object price_ = "";
    /**
     * <code>string price = 1;</code>
     * @return The price.
     */
    public String getPrice() {
      Object ref = price_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string price = 1;</code>
     * @return The bytes for price.
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string price = 1;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      price_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string price = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      price_ = getDefaultInstance().getPrice();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string price = 1;</code>
     * @param value The bytes for price to set.
     * @return This builder for chaining.
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      price_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object quantity_ = "";
    /**
     * <code>string quantity = 2;</code>
     * @return The quantity.
     */
    public String getQuantity() {
      Object ref = quantity_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        quantity_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string quantity = 2;</code>
     * @return The bytes for quantity.
     */
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      Object ref = quantity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        quantity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quantity = 2;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string quantity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      quantity_ = getDefaultInstance().getQuantity();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string quantity = 2;</code>
     * @param value The bytes for quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object amount_ = "";
    /**
     * <code>string amount = 3;</code>
     * @return The amount.
     */
    public String getAmount() {
      Object ref = amount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string amount = 3;</code>
     * @return The bytes for amount.
     */
    public com.google.protobuf.ByteString
        getAmountBytes() {
      Object ref = amount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string amount = 3;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      amount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      amount_ = getDefaultInstance().getAmount();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 3;</code>
     * @param value The bytes for amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      amount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int tradeType_ ;
    /**
     * <code>int32 tradeType = 4;</code>
     * @return The tradeType.
     */
    @Override
    public int getTradeType() {
      return tradeType_;
    }
    /**
     * <code>int32 tradeType = 4;</code>
     * @param value The tradeType to set.
     * @return This builder for chaining.
     */
    public Builder setTradeType(int value) {

      tradeType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tradeType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tradeType_ = 0;
      onChanged();
      return this;
    }

    private boolean isMaker_ ;
    /**
     * <code>bool isMaker = 5;</code>
     * @return The isMaker.
     */
    @Override
    public boolean getIsMaker() {
      return isMaker_;
    }
    /**
     * <code>bool isMaker = 5;</code>
     * @param value The isMaker to set.
     * @return This builder for chaining.
     */
    public Builder setIsMaker(boolean value) {

      isMaker_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool isMaker = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsMaker() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isMaker_ = false;
      onChanged();
      return this;
    }

    private boolean isSelfTrade_ ;
    /**
     * <code>bool isSelfTrade = 6;</code>
     * @return The isSelfTrade.
     */
    @Override
    public boolean getIsSelfTrade() {
      return isSelfTrade_;
    }
    /**
     * <code>bool isSelfTrade = 6;</code>
     * @param value The isSelfTrade to set.
     * @return This builder for chaining.
     */
    public Builder setIsSelfTrade(boolean value) {

      isSelfTrade_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSelfTrade = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSelfTrade() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isSelfTrade_ = false;
      onChanged();
      return this;
    }

    private Object tradeId_ = "";
    /**
     * <code>string tradeId = 7;</code>
     * @return The tradeId.
     */
    public String getTradeId() {
      Object ref = tradeId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tradeId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tradeId = 7;</code>
     * @return The bytes for tradeId.
     */
    public com.google.protobuf.ByteString
        getTradeIdBytes() {
      Object ref = tradeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tradeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tradeId = 7;</code>
     * @param value The tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      tradeId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string tradeId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeId() {
      tradeId_ = getDefaultInstance().getTradeId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string tradeId = 7;</code>
     * @param value The bytes for tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tradeId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object clientOrderId_ = "";
    /**
     * <code>string clientOrderId = 8;</code>
     * @return The clientOrderId.
     */
    public String getClientOrderId() {
      Object ref = clientOrderId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientOrderId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string clientOrderId = 8;</code>
     * @return The bytes for clientOrderId.
     */
    public com.google.protobuf.ByteString
        getClientOrderIdBytes() {
      Object ref = clientOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientOrderId = 8;</code>
     * @param value The clientOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setClientOrderId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      clientOrderId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string clientOrderId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientOrderId() {
      clientOrderId_ = getDefaultInstance().getClientOrderId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string clientOrderId = 8;</code>
     * @param value The bytes for clientOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setClientOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientOrderId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private Object orderId_ = "";
    /**
     * <code>string orderId = 9;</code>
     * @return The orderId.
     */
    public String getOrderId() {
      Object ref = orderId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string orderId = 9;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderId = 9;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      orderId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string orderId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      orderId_ = getDefaultInstance().getOrderId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string orderId = 9;</code>
     * @param value The bytes for orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private Object feeAmount_ = "";
    /**
     * <code>string feeAmount = 10;</code>
     * @return The feeAmount.
     */
    public String getFeeAmount() {
      Object ref = feeAmount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        feeAmount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string feeAmount = 10;</code>
     * @return The bytes for feeAmount.
     */
    public com.google.protobuf.ByteString
        getFeeAmountBytes() {
      Object ref = feeAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        feeAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string feeAmount = 10;</code>
     * @param value The feeAmount to set.
     * @return This builder for chaining.
     */
    public Builder setFeeAmount(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      feeAmount_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string feeAmount = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeeAmount() {
      feeAmount_ = getDefaultInstance().getFeeAmount();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string feeAmount = 10;</code>
     * @param value The bytes for feeAmount to set.
     * @return This builder for chaining.
     */
    public Builder setFeeAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      feeAmount_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private Object feeCurrency_ = "";
    /**
     * <code>string feeCurrency = 11;</code>
     * @return The feeCurrency.
     */
    public String getFeeCurrency() {
      Object ref = feeCurrency_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        feeCurrency_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string feeCurrency = 11;</code>
     * @return The bytes for feeCurrency.
     */
    public com.google.protobuf.ByteString
        getFeeCurrencyBytes() {
      Object ref = feeCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        feeCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string feeCurrency = 11;</code>
     * @param value The feeCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setFeeCurrency(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      feeCurrency_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string feeCurrency = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeeCurrency() {
      feeCurrency_ = getDefaultInstance().getFeeCurrency();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string feeCurrency = 11;</code>
     * @param value The bytes for feeCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setFeeCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      feeCurrency_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <code>int64 time = 12;</code>
     * @return The time.
     */
    @Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 12;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {

      time_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000800);
      time_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PrivateDealsV3Api)
  }

  // @@protoc_insertion_point(class_scope:PrivateDealsV3Api)
  private static final PrivateDealsV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PrivateDealsV3Api();
  }

  public static PrivateDealsV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PrivateDealsV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PrivateDealsV3Api>() {
    @Override
    public PrivateDealsV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PrivateDealsV3Api> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PrivateDealsV3Api> getParserForType() {
    return PARSER;
  }

  @Override
  public PrivateDealsV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

