// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PrivateDealsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PrivateDealsV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrivateDealsV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  String getPrice();
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  String getQuantity();
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  com.google.protobuf.ByteString
      getQuantityBytes();

  /**
   * <code>string amount = 3;</code>
   * @return The amount.
   */
  String getAmount();
  /**
   * <code>string amount = 3;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>int32 tradeType = 4;</code>
   * @return The tradeType.
   */
  int getTradeType();

  /**
   * <code>bool isMaker = 5;</code>
   * @return The isMaker.
   */
  boolean getIsMaker();

  /**
   * <code>bool isSelfTrade = 6;</code>
   * @return The isSelfTrade.
   */
  boolean getIsSelfTrade();

  /**
   * <code>string tradeId = 7;</code>
   * @return The tradeId.
   */
  String getTradeId();
  /**
   * <code>string tradeId = 7;</code>
   * @return The bytes for tradeId.
   */
  com.google.protobuf.ByteString
      getTradeIdBytes();

  /**
   * <code>string clientOrderId = 8;</code>
   * @return The clientOrderId.
   */
  String getClientOrderId();
  /**
   * <code>string clientOrderId = 8;</code>
   * @return The bytes for clientOrderId.
   */
  com.google.protobuf.ByteString
      getClientOrderIdBytes();

  /**
   * <code>string orderId = 9;</code>
   * @return The orderId.
   */
  String getOrderId();
  /**
   * <code>string orderId = 9;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string feeAmount = 10;</code>
   * @return The feeAmount.
   */
  String getFeeAmount();
  /**
   * <code>string feeAmount = 10;</code>
   * @return The bytes for feeAmount.
   */
  com.google.protobuf.ByteString
      getFeeAmountBytes();

  /**
   * <code>string feeCurrency = 11;</code>
   * @return The feeCurrency.
   */
  String getFeeCurrency();
  /**
   * <code>string feeCurrency = 11;</code>
   * @return The bytes for feeCurrency.
   */
  com.google.protobuf.ByteString
      getFeeCurrencyBytes();

  /**
   * <code>int64 time = 12;</code>
   * @return The time.
   */
  long getTime();
}
