// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PrivateDealsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public final class PrivateDealsV3ApiProto {
  private PrivateDealsV3ApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PrivateDealsV3ApiProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrivateDealsV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PrivateDealsV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027PrivateDealsV3Api.proto\"\354\001\n\021PrivateDea" +
      "lsV3Api\022\r\n\005price\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\t" +
      "\022\016\n\006amount\030\003 \001(\t\022\021\n\ttradeType\030\004 \001(\005\022\017\n\007i" +
      "sMaker\030\005 \001(\010\022\023\n\013isSelfTrade\030\006 \001(\010\022\017\n\007tra" +
      "deId\030\007 \001(\t\022\025\n\rclientOrderId\030\010 \001(\t\022\017\n\007ord" +
      "erId\030\t \001(\t\022\021\n\tfeeAmount\030\n \001(\t\022\023\n\013feeCurr" +
      "ency\030\013 \001(\t\022\014\n\004time\030\014 \001(\003B:\n\034com.mxc.push" +
      ".common.protobufB\026PrivateDealsV3ApiProto" +
      "H\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PrivateDealsV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrivateDealsV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PrivateDealsV3Api_descriptor,
        new String[] { "Price", "Quantity", "Amount", "TradeType", "IsMaker", "IsSelfTrade", "TradeId", "ClientOrderId", "OrderId", "FeeAmount", "FeeCurrency", "Time", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
