// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDealsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicAggreDealsV3ApiItem}
 */
public final class PublicAggreDealsV3ApiItem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicAggreDealsV3ApiItem)
    PublicAggreDealsV3ApiItemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicAggreDealsV3ApiItem.class.getName());
  }
  // Use PublicAggreDealsV3ApiItem.newBuilder() to construct.
  private PublicAggreDealsV3ApiItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicAggreDealsV3ApiItem() {
    price_ = "";
    quantity_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3ApiItem_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3ApiItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PublicAggreDealsV3ApiItem.class, Builder.class);
  }

  public static final int PRICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object price_ = "";
  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  @Override
  public String getPrice() {
    Object ref = price_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  @Override
  public com.google.protobuf.ByteString
      getPriceBytes() {
    Object ref = price_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object quantity_ = "";
  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  @Override
  public String getQuantity() {
    Object ref = quantity_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      quantity_ = s;
      return s;
    }
  }
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  @Override
  public com.google.protobuf.ByteString
      getQuantityBytes() {
    Object ref = quantity_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      quantity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADETYPE_FIELD_NUMBER = 3;
  private int tradeType_ = 0;
  /**
   * <code>int32 tradeType = 3;</code>
   * @return The tradeType.
   */
  @Override
  public int getTradeType() {
    return tradeType_;
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private long time_ = 0L;
  /**
   * <code>int64 time = 4;</code>
   * @return The time.
   */
  @Override
  public long getTime() {
    return time_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, quantity_);
    }
    if (tradeType_ != 0) {
      output.writeInt32(3, tradeType_);
    }
    if (time_ != 0L) {
      output.writeInt64(4, time_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, quantity_);
    }
    if (tradeType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tradeType_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, time_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PublicAggreDealsV3ApiItem)) {
      return super.equals(obj);
    }
    PublicAggreDealsV3ApiItem other = (PublicAggreDealsV3ApiItem) obj;

    if (!getPrice()
        .equals(other.getPrice())) return false;
    if (!getQuantity()
        .equals(other.getQuantity())) return false;
    if (getTradeType()
        != other.getTradeType()) return false;
    if (getTime()
        != other.getTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity().hashCode();
    hash = (37 * hash) + TRADETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTradeType();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PublicAggreDealsV3ApiItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PublicAggreDealsV3ApiItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PublicAggreDealsV3ApiItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicAggreDealsV3ApiItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PublicAggreDealsV3ApiItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicAggreDealsV3ApiItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicAggreDealsV3ApiItem)
      PublicAggreDealsV3ApiItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3ApiItem_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3ApiItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicAggreDealsV3ApiItem.class, Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicAggreDealsV3ApiItem.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      price_ = "";
      quantity_ = "";
      tradeType_ = 0;
      time_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3ApiItem_descriptor;
    }

    @Override
    public PublicAggreDealsV3ApiItem getDefaultInstanceForType() {
      return PublicAggreDealsV3ApiItem.getDefaultInstance();
    }

    @Override
    public PublicAggreDealsV3ApiItem build() {
      PublicAggreDealsV3ApiItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PublicAggreDealsV3ApiItem buildPartial() {
      PublicAggreDealsV3ApiItem result = new PublicAggreDealsV3ApiItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(PublicAggreDealsV3ApiItem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tradeType_ = tradeType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.time_ = time_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PublicAggreDealsV3ApiItem) {
        return mergeFrom((PublicAggreDealsV3ApiItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PublicAggreDealsV3ApiItem other) {
      if (other == PublicAggreDealsV3ApiItem.getDefaultInstance()) return this;
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getQuantity().isEmpty()) {
        quantity_ = other.quantity_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTradeType() != 0) {
        setTradeType(other.getTradeType());
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              price_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              quantity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tradeType_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              time_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object price_ = "";
    /**
     * <code>string price = 1;</code>
     * @return The price.
     */
    public String getPrice() {
      Object ref = price_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string price = 1;</code>
     * @return The bytes for price.
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string price = 1;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      price_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string price = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      price_ = getDefaultInstance().getPrice();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string price = 1;</code>
     * @param value The bytes for price to set.
     * @return This builder for chaining.
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      price_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object quantity_ = "";
    /**
     * <code>string quantity = 2;</code>
     * @return The quantity.
     */
    public String getQuantity() {
      Object ref = quantity_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        quantity_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string quantity = 2;</code>
     * @return The bytes for quantity.
     */
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      Object ref = quantity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        quantity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quantity = 2;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string quantity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      quantity_ = getDefaultInstance().getQuantity();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string quantity = 2;</code>
     * @param value The bytes for quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int tradeType_ ;
    /**
     * <code>int32 tradeType = 3;</code>
     * @return The tradeType.
     */
    @Override
    public int getTradeType() {
      return tradeType_;
    }
    /**
     * <code>int32 tradeType = 3;</code>
     * @param value The tradeType to set.
     * @return This builder for chaining.
     */
    public Builder setTradeType(int value) {

      tradeType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tradeType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tradeType_ = 0;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    @Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 4;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {

      time_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      time_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PublicAggreDealsV3ApiItem)
  }

  // @@protoc_insertion_point(class_scope:PublicAggreDealsV3ApiItem)
  private static final PublicAggreDealsV3ApiItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PublicAggreDealsV3ApiItem();
  }

  public static PublicAggreDealsV3ApiItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicAggreDealsV3ApiItem>
      PARSER = new com.google.protobuf.AbstractParser<PublicAggreDealsV3ApiItem>() {
    @Override
    public PublicAggreDealsV3ApiItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicAggreDealsV3ApiItem> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PublicAggreDealsV3ApiItem> getParserForType() {
    return PARSER;
  }

  @Override
  public PublicAggreDealsV3ApiItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

