// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDealsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicAggreDealsV3Api}
 */
public final class PublicAggreDealsV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicAggreDealsV3Api)
    PublicAggreDealsV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicAggreDealsV3Api.class.getName());
  }
  // Use PublicAggreDealsV3Api.newBuilder() to construct.
  private PublicAggreDealsV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicAggreDealsV3Api() {
    deals_ = java.util.Collections.emptyList();
    eventType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3Api_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PublicAggreDealsV3Api.class, Builder.class);
  }

  public static final int DEALS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<PublicAggreDealsV3ApiItem> deals_;
  /**
   * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
   */
  @Override
  public java.util.List<PublicAggreDealsV3ApiItem> getDealsList() {
    return deals_;
  }
  /**
   * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
   */
  @Override
  public java.util.List<? extends PublicAggreDealsV3ApiItemOrBuilder>
      getDealsOrBuilderList() {
    return deals_;
  }
  /**
   * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
   */
  @Override
  public int getDealsCount() {
    return deals_.size();
  }
  /**
   * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
   */
  @Override
  public PublicAggreDealsV3ApiItem getDeals(int index) {
    return deals_.get(index);
  }
  /**
   * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
   */
  @Override
  public PublicAggreDealsV3ApiItemOrBuilder getDealsOrBuilder(
      int index) {
    return deals_.get(index);
  }

  public static final int EVENTTYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object eventType_ = "";
  /**
   * <code>string eventType = 2;</code>
   * @return The eventType.
   */
  @Override
  public String getEventType() {
    Object ref = eventType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <code>string eventType = 2;</code>
   * @return The bytes for eventType.
   */
  @Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    Object ref = eventType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < deals_.size(); i++) {
      output.writeMessage(1, deals_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, eventType_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < deals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, deals_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, eventType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PublicAggreDealsV3Api)) {
      return super.equals(obj);
    }
    PublicAggreDealsV3Api other = (PublicAggreDealsV3Api) obj;

    if (!getDealsList()
        .equals(other.getDealsList())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDealsCount() > 0) {
      hash = (37 * hash) + DEALS_FIELD_NUMBER;
      hash = (53 * hash) + getDealsList().hashCode();
    }
    hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PublicAggreDealsV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicAggreDealsV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicAggreDealsV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicAggreDealsV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicAggreDealsV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicAggreDealsV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicAggreDealsV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicAggreDealsV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PublicAggreDealsV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PublicAggreDealsV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PublicAggreDealsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicAggreDealsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PublicAggreDealsV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicAggreDealsV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicAggreDealsV3Api)
      PublicAggreDealsV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3Api_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicAggreDealsV3Api.class, Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicAggreDealsV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (dealsBuilder_ == null) {
        deals_ = java.util.Collections.emptyList();
      } else {
        deals_ = null;
        dealsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      eventType_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PublicAggreDealsV3ApiProto.internal_static_PublicAggreDealsV3Api_descriptor;
    }

    @Override
    public PublicAggreDealsV3Api getDefaultInstanceForType() {
      return PublicAggreDealsV3Api.getDefaultInstance();
    }

    @Override
    public PublicAggreDealsV3Api build() {
      PublicAggreDealsV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PublicAggreDealsV3Api buildPartial() {
      PublicAggreDealsV3Api result = new PublicAggreDealsV3Api(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(PublicAggreDealsV3Api result) {
      if (dealsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          deals_ = java.util.Collections.unmodifiableList(deals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.deals_ = deals_;
      } else {
        result.deals_ = dealsBuilder_.build();
      }
    }

    private void buildPartial0(PublicAggreDealsV3Api result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.eventType_ = eventType_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PublicAggreDealsV3Api) {
        return mergeFrom((PublicAggreDealsV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PublicAggreDealsV3Api other) {
      if (other == PublicAggreDealsV3Api.getDefaultInstance()) return this;
      if (dealsBuilder_ == null) {
        if (!other.deals_.isEmpty()) {
          if (deals_.isEmpty()) {
            deals_ = other.deals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDealsIsMutable();
            deals_.addAll(other.deals_);
          }
          onChanged();
        }
      } else {
        if (!other.deals_.isEmpty()) {
          if (dealsBuilder_.isEmpty()) {
            dealsBuilder_.dispose();
            dealsBuilder_ = null;
            deals_ = other.deals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dealsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getDealsFieldBuilder() : null;
          } else {
            dealsBuilder_.addAllMessages(other.deals_);
          }
        }
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              PublicAggreDealsV3ApiItem m =
                  input.readMessage(
                      PublicAggreDealsV3ApiItem.parser(),
                      extensionRegistry);
              if (dealsBuilder_ == null) {
                ensureDealsIsMutable();
                deals_.add(m);
              } else {
                dealsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<PublicAggreDealsV3ApiItem> deals_ =
      java.util.Collections.emptyList();
    private void ensureDealsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        deals_ = new java.util.ArrayList<PublicAggreDealsV3ApiItem>(deals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        PublicAggreDealsV3ApiItem, PublicAggreDealsV3ApiItem.Builder, PublicAggreDealsV3ApiItemOrBuilder> dealsBuilder_;

    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public java.util.List<PublicAggreDealsV3ApiItem> getDealsList() {
      if (dealsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deals_);
      } else {
        return dealsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public int getDealsCount() {
      if (dealsBuilder_ == null) {
        return deals_.size();
      } else {
        return dealsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public PublicAggreDealsV3ApiItem getDeals(int index) {
      if (dealsBuilder_ == null) {
        return deals_.get(index);
      } else {
        return dealsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder setDeals(
        int index, PublicAggreDealsV3ApiItem value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.set(index, value);
        onChanged();
      } else {
        dealsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder setDeals(
        int index, PublicAggreDealsV3ApiItem.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.set(index, builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder addDeals(PublicAggreDealsV3ApiItem value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.add(value);
        onChanged();
      } else {
        dealsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder addDeals(
        int index, PublicAggreDealsV3ApiItem value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.add(index, value);
        onChanged();
      } else {
        dealsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder addDeals(
        PublicAggreDealsV3ApiItem.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.add(builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder addDeals(
        int index, PublicAggreDealsV3ApiItem.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.add(index, builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder addAllDeals(
        Iterable<? extends PublicAggreDealsV3ApiItem> values) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deals_);
        onChanged();
      } else {
        dealsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder clearDeals() {
      if (dealsBuilder_ == null) {
        deals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dealsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public Builder removeDeals(int index) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.remove(index);
        onChanged();
      } else {
        dealsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public PublicAggreDealsV3ApiItem.Builder getDealsBuilder(
        int index) {
      return getDealsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public PublicAggreDealsV3ApiItemOrBuilder getDealsOrBuilder(
        int index) {
      if (dealsBuilder_ == null) {
        return deals_.get(index);  } else {
        return dealsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public java.util.List<? extends PublicAggreDealsV3ApiItemOrBuilder>
         getDealsOrBuilderList() {
      if (dealsBuilder_ != null) {
        return dealsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deals_);
      }
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public PublicAggreDealsV3ApiItem.Builder addDealsBuilder() {
      return getDealsFieldBuilder().addBuilder(
          PublicAggreDealsV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public PublicAggreDealsV3ApiItem.Builder addDealsBuilder(
        int index) {
      return getDealsFieldBuilder().addBuilder(
          index, PublicAggreDealsV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicAggreDealsV3ApiItem deals = 1;</code>
     */
    public java.util.List<PublicAggreDealsV3ApiItem.Builder>
         getDealsBuilderList() {
      return getDealsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        PublicAggreDealsV3ApiItem, PublicAggreDealsV3ApiItem.Builder, PublicAggreDealsV3ApiItemOrBuilder>
        getDealsFieldBuilder() {
      if (dealsBuilder_ == null) {
        dealsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            PublicAggreDealsV3ApiItem, PublicAggreDealsV3ApiItem.Builder, PublicAggreDealsV3ApiItemOrBuilder>(
                deals_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        deals_ = null;
      }
      return dealsBuilder_;
    }

    private Object eventType_ = "";
    /**
     * <code>string eventType = 2;</code>
     * @return The eventType.
     */
    public String getEventType() {
      Object ref = eventType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string eventType = 2;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventType = 2;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string eventType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string eventType = 2;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PublicAggreDealsV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicAggreDealsV3Api)
  private static final PublicAggreDealsV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PublicAggreDealsV3Api();
  }

  public static PublicAggreDealsV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicAggreDealsV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicAggreDealsV3Api>() {
    @Override
    public PublicAggreDealsV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicAggreDealsV3Api> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PublicAggreDealsV3Api> getParserForType() {
    return PARSER;
  }

  @Override
  public PublicAggreDealsV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

