// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicLimitDepthsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicLimitDepthsV3Api}
 */
public final class PublicLimitDepthsV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicLimitDepthsV3Api)
    PublicLimitDepthsV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicLimitDepthsV3Api.class.getName());
  }
  // Use PublicLimitDepthsV3Api.newBuilder() to construct.
  private PublicLimitDepthsV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicLimitDepthsV3Api() {
    asks_ = java.util.Collections.emptyList();
    bids_ = java.util.Collections.emptyList();
    eventType_ = "";
    version_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PublicLimitDepthsV3ApiProto.internal_static_PublicLimitDepthsV3Api_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PublicLimitDepthsV3ApiProto.internal_static_PublicLimitDepthsV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PublicLimitDepthsV3Api.class, Builder.class);
  }

  public static final int ASKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<PublicLimitDepthV3ApiItem> asks_;
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
   */
  @Override
  public java.util.List<PublicLimitDepthV3ApiItem> getAsksList() {
    return asks_;
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
   */
  @Override
  public java.util.List<? extends PublicLimitDepthV3ApiItemOrBuilder>
      getAsksOrBuilderList() {
    return asks_;
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
   */
  @Override
  public int getAsksCount() {
    return asks_.size();
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
   */
  @Override
  public PublicLimitDepthV3ApiItem getAsks(int index) {
    return asks_.get(index);
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
   */
  @Override
  public PublicLimitDepthV3ApiItemOrBuilder getAsksOrBuilder(
      int index) {
    return asks_.get(index);
  }

  public static final int BIDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<PublicLimitDepthV3ApiItem> bids_;
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
   */
  @Override
  public java.util.List<PublicLimitDepthV3ApiItem> getBidsList() {
    return bids_;
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
   */
  @Override
  public java.util.List<? extends PublicLimitDepthV3ApiItemOrBuilder>
      getBidsOrBuilderList() {
    return bids_;
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
   */
  @Override
  public int getBidsCount() {
    return bids_.size();
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
   */
  @Override
  public PublicLimitDepthV3ApiItem getBids(int index) {
    return bids_.get(index);
  }
  /**
   * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
   */
  @Override
  public PublicLimitDepthV3ApiItemOrBuilder getBidsOrBuilder(
      int index) {
    return bids_.get(index);
  }

  public static final int EVENTTYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object eventType_ = "";
  /**
   * <code>string eventType = 3;</code>
   * @return The eventType.
   */
  @Override
  public String getEventType() {
    Object ref = eventType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <code>string eventType = 3;</code>
   * @return The bytes for eventType.
   */
  @Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    Object ref = eventType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object version_ = "";
  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  @Override
  public String getVersion() {
    Object ref = version_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  @Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    Object ref = version_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < asks_.size(); i++) {
      output.writeMessage(1, asks_.get(i));
    }
    for (int i = 0; i < bids_.size(); i++) {
      output.writeMessage(2, bids_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, version_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < asks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, asks_.get(i));
    }
    for (int i = 0; i < bids_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, bids_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, version_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PublicLimitDepthsV3Api)) {
      return super.equals(obj);
    }
    PublicLimitDepthsV3Api other = (PublicLimitDepthsV3Api) obj;

    if (!getAsksList()
        .equals(other.getAsksList())) return false;
    if (!getBidsList()
        .equals(other.getBidsList())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAsksCount() > 0) {
      hash = (37 * hash) + ASKS_FIELD_NUMBER;
      hash = (53 * hash) + getAsksList().hashCode();
    }
    if (getBidsCount() > 0) {
      hash = (37 * hash) + BIDS_FIELD_NUMBER;
      hash = (53 * hash) + getBidsList().hashCode();
    }
    hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PublicLimitDepthsV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicLimitDepthsV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicLimitDepthsV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PublicLimitDepthsV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PublicLimitDepthsV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicLimitDepthsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PublicLimitDepthsV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicLimitDepthsV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicLimitDepthsV3Api)
      PublicLimitDepthsV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicLimitDepthsV3ApiProto.internal_static_PublicLimitDepthsV3Api_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicLimitDepthsV3ApiProto.internal_static_PublicLimitDepthsV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicLimitDepthsV3Api.class, Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicLimitDepthsV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
      } else {
        asks_ = null;
        asksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
      } else {
        bids_ = null;
        bidsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      eventType_ = "";
      version_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PublicLimitDepthsV3ApiProto.internal_static_PublicLimitDepthsV3Api_descriptor;
    }

    @Override
    public PublicLimitDepthsV3Api getDefaultInstanceForType() {
      return PublicLimitDepthsV3Api.getDefaultInstance();
    }

    @Override
    public PublicLimitDepthsV3Api build() {
      PublicLimitDepthsV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PublicLimitDepthsV3Api buildPartial() {
      PublicLimitDepthsV3Api result = new PublicLimitDepthsV3Api(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(PublicLimitDepthsV3Api result) {
      if (asksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          asks_ = java.util.Collections.unmodifiableList(asks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.asks_ = asks_;
      } else {
        result.asks_ = asksBuilder_.build();
      }
      if (bidsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          bids_ = java.util.Collections.unmodifiableList(bids_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.bids_ = bids_;
      } else {
        result.bids_ = bidsBuilder_.build();
      }
    }

    private void buildPartial0(PublicLimitDepthsV3Api result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.eventType_ = eventType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.version_ = version_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PublicLimitDepthsV3Api) {
        return mergeFrom((PublicLimitDepthsV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PublicLimitDepthsV3Api other) {
      if (other == PublicLimitDepthsV3Api.getDefaultInstance()) return this;
      if (asksBuilder_ == null) {
        if (!other.asks_.isEmpty()) {
          if (asks_.isEmpty()) {
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAsksIsMutable();
            asks_.addAll(other.asks_);
          }
          onChanged();
        }
      } else {
        if (!other.asks_.isEmpty()) {
          if (asksBuilder_.isEmpty()) {
            asksBuilder_.dispose();
            asksBuilder_ = null;
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            asksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAsksFieldBuilder() : null;
          } else {
            asksBuilder_.addAllMessages(other.asks_);
          }
        }
      }
      if (bidsBuilder_ == null) {
        if (!other.bids_.isEmpty()) {
          if (bids_.isEmpty()) {
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBidsIsMutable();
            bids_.addAll(other.bids_);
          }
          onChanged();
        }
      } else {
        if (!other.bids_.isEmpty()) {
          if (bidsBuilder_.isEmpty()) {
            bidsBuilder_.dispose();
            bidsBuilder_ = null;
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000002);
            bidsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getBidsFieldBuilder() : null;
          } else {
            bidsBuilder_.addAllMessages(other.bids_);
          }
        }
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              PublicLimitDepthV3ApiItem m =
                  input.readMessage(
                      PublicLimitDepthV3ApiItem.parser(),
                      extensionRegistry);
              if (asksBuilder_ == null) {
                ensureAsksIsMutable();
                asks_.add(m);
              } else {
                asksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              PublicLimitDepthV3ApiItem m =
                  input.readMessage(
                      PublicLimitDepthV3ApiItem.parser(),
                      extensionRegistry);
              if (bidsBuilder_ == null) {
                ensureBidsIsMutable();
                bids_.add(m);
              } else {
                bidsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<PublicLimitDepthV3ApiItem> asks_ =
      java.util.Collections.emptyList();
    private void ensureAsksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        asks_ = new java.util.ArrayList<PublicLimitDepthV3ApiItem>(asks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        PublicLimitDepthV3ApiItem, PublicLimitDepthV3ApiItem.Builder, PublicLimitDepthV3ApiItemOrBuilder> asksBuilder_;

    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public java.util.List<PublicLimitDepthV3ApiItem> getAsksList() {
      if (asksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(asks_);
      } else {
        return asksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public int getAsksCount() {
      if (asksBuilder_ == null) {
        return asks_.size();
      } else {
        return asksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public PublicLimitDepthV3ApiItem getAsks(int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);
      } else {
        return asksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder setAsks(
        int index, PublicLimitDepthV3ApiItem value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.set(index, value);
        onChanged();
      } else {
        asksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder setAsks(
        int index, PublicLimitDepthV3ApiItem.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.set(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(PublicLimitDepthV3ApiItem value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(value);
        onChanged();
      } else {
        asksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(
        int index, PublicLimitDepthV3ApiItem value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(index, value);
        onChanged();
      } else {
        asksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(
        PublicLimitDepthV3ApiItem.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(
        int index, PublicLimitDepthV3ApiItem.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAllAsks(
        Iterable<? extends PublicLimitDepthV3ApiItem> values) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, asks_);
        onChanged();
      } else {
        asksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder clearAsks() {
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        asksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public Builder removeAsks(int index) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.remove(index);
        onChanged();
      } else {
        asksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public PublicLimitDepthV3ApiItem.Builder getAsksBuilder(
        int index) {
      return getAsksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public PublicLimitDepthV3ApiItemOrBuilder getAsksOrBuilder(
        int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);  } else {
        return asksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public java.util.List<? extends PublicLimitDepthV3ApiItemOrBuilder>
         getAsksOrBuilderList() {
      if (asksBuilder_ != null) {
        return asksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(asks_);
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public PublicLimitDepthV3ApiItem.Builder addAsksBuilder() {
      return getAsksFieldBuilder().addBuilder(
          PublicLimitDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public PublicLimitDepthV3ApiItem.Builder addAsksBuilder(
        int index) {
      return getAsksFieldBuilder().addBuilder(
          index, PublicLimitDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem asks = 1;</code>
     */
    public java.util.List<PublicLimitDepthV3ApiItem.Builder>
         getAsksBuilderList() {
      return getAsksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        PublicLimitDepthV3ApiItem, PublicLimitDepthV3ApiItem.Builder, PublicLimitDepthV3ApiItemOrBuilder>
        getAsksFieldBuilder() {
      if (asksBuilder_ == null) {
        asksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            PublicLimitDepthV3ApiItem, PublicLimitDepthV3ApiItem.Builder, PublicLimitDepthV3ApiItemOrBuilder>(
                asks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        asks_ = null;
      }
      return asksBuilder_;
    }

    private java.util.List<PublicLimitDepthV3ApiItem> bids_ =
      java.util.Collections.emptyList();
    private void ensureBidsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        bids_ = new java.util.ArrayList<PublicLimitDepthV3ApiItem>(bids_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        PublicLimitDepthV3ApiItem, PublicLimitDepthV3ApiItem.Builder, PublicLimitDepthV3ApiItemOrBuilder> bidsBuilder_;

    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public java.util.List<PublicLimitDepthV3ApiItem> getBidsList() {
      if (bidsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bids_);
      } else {
        return bidsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public int getBidsCount() {
      if (bidsBuilder_ == null) {
        return bids_.size();
      } else {
        return bidsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public PublicLimitDepthV3ApiItem getBids(int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);
      } else {
        return bidsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder setBids(
        int index, PublicLimitDepthV3ApiItem value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.set(index, value);
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder setBids(
        int index, PublicLimitDepthV3ApiItem.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.set(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(PublicLimitDepthV3ApiItem value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(
        int index, PublicLimitDepthV3ApiItem value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(index, value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(
        PublicLimitDepthV3ApiItem.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(
        int index, PublicLimitDepthV3ApiItem.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder addAllBids(
        Iterable<? extends PublicLimitDepthV3ApiItem> values) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bids_);
        onChanged();
      } else {
        bidsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder clearBids() {
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        bidsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public Builder removeBids(int index) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.remove(index);
        onChanged();
      } else {
        bidsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public PublicLimitDepthV3ApiItem.Builder getBidsBuilder(
        int index) {
      return getBidsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public PublicLimitDepthV3ApiItemOrBuilder getBidsOrBuilder(
        int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);  } else {
        return bidsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public java.util.List<? extends PublicLimitDepthV3ApiItemOrBuilder>
         getBidsOrBuilderList() {
      if (bidsBuilder_ != null) {
        return bidsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bids_);
      }
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public PublicLimitDepthV3ApiItem.Builder addBidsBuilder() {
      return getBidsFieldBuilder().addBuilder(
          PublicLimitDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public PublicLimitDepthV3ApiItem.Builder addBidsBuilder(
        int index) {
      return getBidsFieldBuilder().addBuilder(
          index, PublicLimitDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicLimitDepthV3ApiItem bids = 2;</code>
     */
    public java.util.List<PublicLimitDepthV3ApiItem.Builder>
         getBidsBuilderList() {
      return getBidsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        PublicLimitDepthV3ApiItem, PublicLimitDepthV3ApiItem.Builder, PublicLimitDepthV3ApiItemOrBuilder>
        getBidsFieldBuilder() {
      if (bidsBuilder_ == null) {
        bidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            PublicLimitDepthV3ApiItem, PublicLimitDepthV3ApiItem.Builder, PublicLimitDepthV3ApiItemOrBuilder>(
                bids_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        bids_ = null;
      }
      return bidsBuilder_;
    }

    private Object eventType_ = "";
    /**
     * <code>string eventType = 3;</code>
     * @return The eventType.
     */
    public String getEventType() {
      Object ref = eventType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string eventType = 3;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventType = 3;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string eventType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string eventType = 3;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object version_ = "";
    /**
     * <code>string version = 4;</code>
     * @return The version.
     */
    public String getVersion() {
      Object ref = version_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 4;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 4;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PublicLimitDepthsV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicLimitDepthsV3Api)
  private static final PublicLimitDepthsV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PublicLimitDepthsV3Api();
  }

  public static PublicLimitDepthsV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicLimitDepthsV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicLimitDepthsV3Api>() {
    @Override
    public PublicLimitDepthsV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicLimitDepthsV3Api> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PublicLimitDepthsV3Api> getParserForType() {
    return PARSER;
  }

  @Override
  public PublicLimitDepthsV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

