// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreBookTickerV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PublicAggreBookTickerV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicAggreBookTickerV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bidPrice = 1;</code>
   * @return The bidPrice.
   */
  String getBidPrice();
  /**
   * <code>string bidPrice = 1;</code>
   * @return The bytes for bidPrice.
   */
  com.google.protobuf.ByteString
      getBidPriceBytes();

  /**
   * <code>string bidQuantity = 2;</code>
   * @return The bidQuantity.
   */
  String getBidQuantity();
  /**
   * <code>string bidQuantity = 2;</code>
   * @return The bytes for bidQuantity.
   */
  com.google.protobuf.ByteString
      getBidQuantityBytes();

  /**
   * <code>string askPrice = 3;</code>
   * @return The askPrice.
   */
  String getAskPrice();
  /**
   * <code>string askPrice = 3;</code>
   * @return The bytes for askPrice.
   */
  com.google.protobuf.ByteString
      getAskPriceBytes();

  /**
   * <code>string askQuantity = 4;</code>
   * @return The askQuantity.
   */
  String getAskQuantity();
  /**
   * <code>string askQuantity = 4;</code>
   * @return The bytes for askQuantity.
   */
  com.google.protobuf.ByteString
      getAskQuantityBytes();
}
