// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicMiniTickersV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public final class PublicMiniTickersV3ApiProto {
  private PublicMiniTickersV3ApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicMiniTickersV3ApiProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicMiniTickersV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicMiniTickersV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034PublicMiniTickersV3Api.proto\032\033PublicMi" +
      "niTickerV3Api.proto\"?\n\026PublicMiniTickers" +
      "V3Api\022%\n\005items\030\001 \003(\0132\026.PublicMiniTickerV" +
      "3ApiB?\n\034com.mxc.push.common.protobufB\033Pu" +
      "blicMiniTickersV3ApiProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PublicMiniTickerV3ApiProto.getDescriptor(),
        });
    internal_static_PublicMiniTickersV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicMiniTickersV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PublicMiniTickersV3Api_descriptor,
        new String[] { "Items", });
    descriptor.resolveAllFeaturesImmutable();
    PublicMiniTickerV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
