// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicIncreaseDepthsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PublicIncreaseDepthsV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicIncreaseDepthsV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem asks = 1;</code>
   */
  java.util.List<PublicIncreaseDepthV3ApiItem>
      getAsksList();
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem asks = 1;</code>
   */
  PublicIncreaseDepthV3ApiItem getAsks(int index);
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem asks = 1;</code>
   */
  int getAsksCount();
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem asks = 1;</code>
   */
  java.util.List<? extends PublicIncreaseDepthV3ApiItemOrBuilder>
      getAsksOrBuilderList();
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem asks = 1;</code>
   */
  PublicIncreaseDepthV3ApiItemOrBuilder getAsksOrBuilder(
      int index);

  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem bids = 2;</code>
   */
  java.util.List<PublicIncreaseDepthV3ApiItem>
      getBidsList();
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem bids = 2;</code>
   */
  PublicIncreaseDepthV3ApiItem getBids(int index);
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem bids = 2;</code>
   */
  int getBidsCount();
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem bids = 2;</code>
   */
  java.util.List<? extends PublicIncreaseDepthV3ApiItemOrBuilder>
      getBidsOrBuilderList();
  /**
   * <code>repeated .PublicIncreaseDepthV3ApiItem bids = 2;</code>
   */
  PublicIncreaseDepthV3ApiItemOrBuilder getBidsOrBuilder(
      int index);

  /**
   * <code>string eventType = 3;</code>
   * @return The eventType.
   */
  String getEventType();
  /**
   * <code>string eventType = 3;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
