// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicIncreaseDepthsBatchV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PublicIncreaseDepthsBatchV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicIncreaseDepthsBatchV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  java.util.List<PublicIncreaseDepthsV3Api>
      getItemsList();
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  PublicIncreaseDepthsV3Api getItems(int index);
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  java.util.List<? extends PublicIncreaseDepthsV3ApiOrBuilder>
      getItemsOrBuilderList();
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  PublicIncreaseDepthsV3ApiOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>string eventType = 2;</code>
   * @return The eventType.
   */
  String getEventType();
  /**
   * <code>string eventType = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();
}
