// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicSpotKlineV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PublicSpotKlineV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicSpotKlineV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
   * </pre>
   *
   * <code>string interval = 1;</code>
   * @return The interval.
   */
  String getInterval();
  /**
   * <pre>
   * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
   * </pre>
   *
   * <code>string interval = 1;</code>
   * @return The bytes for interval.
   */
  com.google.protobuf.ByteString
      getIntervalBytes();

  /**
   * <pre>
   * 窗口开始时间戳(秒时间戳)
   * </pre>
   *
   * <code>int64 windowStart = 2;</code>
   * @return The windowStart.
   */
  long getWindowStart();

  /**
   * <pre>
   * 开盘价
   * </pre>
   *
   * <code>string openingPrice = 3;</code>
   * @return The openingPrice.
   */
  String getOpeningPrice();
  /**
   * <pre>
   * 开盘价
   * </pre>
   *
   * <code>string openingPrice = 3;</code>
   * @return The bytes for openingPrice.
   */
  com.google.protobuf.ByteString
      getOpeningPriceBytes();

  /**
   * <pre>
   * 收盘价
   * </pre>
   *
   * <code>string closingPrice = 4;</code>
   * @return The closingPrice.
   */
  String getClosingPrice();
  /**
   * <pre>
   * 收盘价
   * </pre>
   *
   * <code>string closingPrice = 4;</code>
   * @return The bytes for closingPrice.
   */
  com.google.protobuf.ByteString
      getClosingPriceBytes();

  /**
   * <pre>
   * 最高价
   * </pre>
   *
   * <code>string highestPrice = 5;</code>
   * @return The highestPrice.
   */
  String getHighestPrice();
  /**
   * <pre>
   * 最高价
   * </pre>
   *
   * <code>string highestPrice = 5;</code>
   * @return The bytes for highestPrice.
   */
  com.google.protobuf.ByteString
      getHighestPriceBytes();

  /**
   * <pre>
   * 最低价
   * </pre>
   *
   * <code>string lowestPrice = 6;</code>
   * @return The lowestPrice.
   */
  String getLowestPrice();
  /**
   * <pre>
   * 最低价
   * </pre>
   *
   * <code>string lowestPrice = 6;</code>
   * @return The bytes for lowestPrice.
   */
  com.google.protobuf.ByteString
      getLowestPriceBytes();

  /**
   * <pre>
   * 成交量
   * </pre>
   *
   * <code>string volume = 7;</code>
   * @return The volume.
   */
  String getVolume();
  /**
   * <pre>
   * 成交量
   * </pre>
   *
   * <code>string volume = 7;</code>
   * @return The bytes for volume.
   */
  com.google.protobuf.ByteString
      getVolumeBytes();

  /**
   * <pre>
   * 成交额
   * </pre>
   *
   * <code>string amount = 8;</code>
   * @return The amount.
   */
  String getAmount();
  /**
   * <pre>
   * 成交额
   * </pre>
   *
   * <code>string amount = 8;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <pre>
   * 窗口结束时间戳(秒时间戳)
   * </pre>
   *
   * <code>int64 windowEnd = 9;</code>
   * @return The windowEnd.
   */
  long getWindowEnd();
}
