// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDealsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public final class PublicAggreDealsV3ApiProto {
  private PublicAggreDealsV3ApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicAggreDealsV3ApiProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicAggreDealsV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicAggreDealsV3Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicAggreDealsV3ApiItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicAggreDealsV3ApiItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033PublicAggreDealsV3Api.proto\"U\n\025PublicA" +
      "ggreDealsV3Api\022)\n\005deals\030\001 \003(\0132\032.PublicAg" +
      "greDealsV3ApiItem\022\021\n\teventType\030\002 \001(\t\"]\n\031" +
      "PublicAggreDealsV3ApiItem\022\r\n\005price\030\001 \001(\t" +
      "\022\020\n\010quantity\030\002 \001(\t\022\021\n\ttradeType\030\003 \001(\005\022\014\n" +
      "\004time\030\004 \001(\003B>\n\034com.mxc.push.common.proto" +
      "bufB\032PublicAggreDealsV3ApiProtoH\001P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicAggreDealsV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicAggreDealsV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PublicAggreDealsV3Api_descriptor,
        new String[] { "Deals", "EventType", });
    internal_static_PublicAggreDealsV3ApiItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicAggreDealsV3ApiItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PublicAggreDealsV3ApiItem_descriptor,
        new String[] { "Price", "Quantity", "TradeType", "Time", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
