// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDepthsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PublicAggreDepthV3ApiItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicAggreDepthV3ApiItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  String getPrice();
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  String getQuantity();
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  com.google.protobuf.ByteString
      getQuantityBytes();
}
