// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicIncreaseDepthsBatchV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public final class PublicIncreaseDepthsBatchV3ApiProto {
  private PublicIncreaseDepthsBatchV3ApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicIncreaseDepthsBatchV3ApiProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicIncreaseDepthsBatchV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicIncreaseDepthsBatchV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$PublicIncreaseDepthsBatchV3Api.proto\032\037" +
      "PublicIncreaseDepthsV3Api.proto\"^\n\036Publi" +
      "cIncreaseDepthsBatchV3Api\022)\n\005items\030\001 \003(\013" +
      "2\032.PublicIncreaseDepthsV3Api\022\021\n\teventTyp" +
      "e\030\002 \001(\tBG\n\034com.mxc.push.common.protobufB" +
      "#PublicIncreaseDepthsBatchV3ApiProtoH\001P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PublicIncreaseDepthsV3ApiProto.getDescriptor(),
        });
    internal_static_PublicIncreaseDepthsBatchV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicIncreaseDepthsBatchV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PublicIncreaseDepthsBatchV3Api_descriptor,
        new String[] { "Items", "EventType", });
    descriptor.resolveAllFeaturesImmutable();
    PublicIncreaseDepthsV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
