// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicBookTickerBatchV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicBookTickerBatchV3Api}
 */
public final class PublicBookTickerBatchV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicBookTickerBatchV3Api)
    PublicBookTickerBatchV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublicBookTickerBatchV3Api.class.getName());
  }
  // Use PublicBookTickerBatchV3Api.newBuilder() to construct.
  private PublicBookTickerBatchV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicBookTickerBatchV3Api() {
    items_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PublicBookTickerBatchV3ApiProto.internal_static_PublicBookTickerBatchV3Api_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PublicBookTickerBatchV3ApiProto.internal_static_PublicBookTickerBatchV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PublicBookTickerBatchV3Api.class, Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<PublicBookTickerV3Api> items_;
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  @Override
  public java.util.List<PublicBookTickerV3Api> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  @Override
  public java.util.List<? extends PublicBookTickerV3ApiOrBuilder>
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  @Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  @Override
  public PublicBookTickerV3Api getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  @Override
  public PublicBookTickerV3ApiOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PublicBookTickerBatchV3Api)) {
      return super.equals(obj);
    }
    PublicBookTickerBatchV3Api other = (PublicBookTickerBatchV3Api) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PublicBookTickerBatchV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicBookTickerBatchV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublicBookTickerBatchV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PublicBookTickerBatchV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PublicBookTickerBatchV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PublicBookTickerBatchV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PublicBookTickerBatchV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicBookTickerBatchV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicBookTickerBatchV3Api)
      PublicBookTickerBatchV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicBookTickerBatchV3ApiProto.internal_static_PublicBookTickerBatchV3Api_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicBookTickerBatchV3ApiProto.internal_static_PublicBookTickerBatchV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicBookTickerBatchV3Api.class, Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicBookTickerBatchV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PublicBookTickerBatchV3ApiProto.internal_static_PublicBookTickerBatchV3Api_descriptor;
    }

    @Override
    public PublicBookTickerBatchV3Api getDefaultInstanceForType() {
      return PublicBookTickerBatchV3Api.getDefaultInstance();
    }

    @Override
    public PublicBookTickerBatchV3Api build() {
      PublicBookTickerBatchV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PublicBookTickerBatchV3Api buildPartial() {
      PublicBookTickerBatchV3Api result = new PublicBookTickerBatchV3Api(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(PublicBookTickerBatchV3Api result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(PublicBookTickerBatchV3Api result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PublicBookTickerBatchV3Api) {
        return mergeFrom((PublicBookTickerBatchV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PublicBookTickerBatchV3Api other) {
      if (other == PublicBookTickerBatchV3Api.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              PublicBookTickerV3Api m =
                  input.readMessage(
                      PublicBookTickerV3Api.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<PublicBookTickerV3Api> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<PublicBookTickerV3Api>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        PublicBookTickerV3Api, PublicBookTickerV3Api.Builder, PublicBookTickerV3ApiOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public java.util.List<PublicBookTickerV3Api> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public PublicBookTickerV3Api getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder setItems(
        int index, PublicBookTickerV3Api value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder setItems(
        int index, PublicBookTickerV3Api.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder addItems(PublicBookTickerV3Api value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder addItems(
        int index, PublicBookTickerV3Api value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder addItems(
        PublicBookTickerV3Api.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder addItems(
        int index, PublicBookTickerV3Api.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder addAllItems(
        Iterable<? extends PublicBookTickerV3Api> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public PublicBookTickerV3Api.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public PublicBookTickerV3ApiOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public java.util.List<? extends PublicBookTickerV3ApiOrBuilder>
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public PublicBookTickerV3Api.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          PublicBookTickerV3Api.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public PublicBookTickerV3Api.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, PublicBookTickerV3Api.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicBookTickerV3Api items = 1;</code>
     */
    public java.util.List<PublicBookTickerV3Api.Builder>
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        PublicBookTickerV3Api, PublicBookTickerV3Api.Builder, PublicBookTickerV3ApiOrBuilder>
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            PublicBookTickerV3Api, PublicBookTickerV3Api.Builder, PublicBookTickerV3ApiOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:PublicBookTickerBatchV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicBookTickerBatchV3Api)
  private static final PublicBookTickerBatchV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PublicBookTickerBatchV3Api();
  }

  public static PublicBookTickerBatchV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicBookTickerBatchV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicBookTickerBatchV3Api>() {
    @Override
    public PublicBookTickerBatchV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicBookTickerBatchV3Api> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PublicBookTickerBatchV3Api> getParserForType() {
    return PARSER;
  }

  @Override
  public PublicBookTickerBatchV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

