// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDepthsV3Api.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public interface PublicAggreDepthsV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicAggreDepthsV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  java.util.List<PublicAggreDepthV3ApiItem>
      getAsksList();
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  PublicAggreDepthV3ApiItem getAsks(int index);
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  int getAsksCount();
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  java.util.List<? extends PublicAggreDepthV3ApiItemOrBuilder>
      getAsksOrBuilderList();
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  PublicAggreDepthV3ApiItemOrBuilder getAsksOrBuilder(
      int index);

  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  java.util.List<PublicAggreDepthV3ApiItem>
      getBidsList();
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  PublicAggreDepthV3ApiItem getBids(int index);
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  int getBidsCount();
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  java.util.List<? extends PublicAggreDepthV3ApiItemOrBuilder>
      getBidsOrBuilderList();
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  PublicAggreDepthV3ApiItemOrBuilder getBidsOrBuilder(
      int index);

  /**
   * <code>string eventType = 3;</code>
   * @return The eventType.
   */
  String getEventType();
  /**
   * <code>string eventType = 3;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>string fromVersion = 4;</code>
   * @return The fromVersion.
   */
  String getFromVersion();
  /**
   * <code>string fromVersion = 4;</code>
   * @return The bytes for fromVersion.
   */
  com.google.protobuf.ByteString
      getFromVersionBytes();

  /**
   * <code>string toVersion = 5;</code>
   * @return The toVersion.
   */
  String getToVersion();
  /**
   * <code>string toVersion = 5;</code>
   * @return The bytes for toVersion.
   */
  com.google.protobuf.ByteString
      getToVersionBytes();
}
