// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PushDataV3ApiWrapper.proto
// Protobuf Java Version: 4.29.3

package com.mxc.push.common.protobuf;

public final class PushDataV3ApiWrapperProto {
  private PushDataV3ApiWrapperProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PushDataV3ApiWrapperProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushDataV3ApiWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PushDataV3ApiWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032PushDataV3ApiWrapper.proto\032\026PublicDeal" +
      "sV3Api.proto\032\037PublicIncreaseDepthsV3Api." +
      "proto\032\034PublicLimitDepthsV3Api.proto\032\030Pri" +
      "vateOrdersV3Api.proto\032\033PublicBookTickerV" +
      "3Api.proto\032\027PrivateDealsV3Api.proto\032\031Pri" +
      "vateAccountV3Api.proto\032\032PublicSpotKlineV" +
      "3Api.proto\032\033PublicMiniTickerV3Api.proto\032" +
      "\034PublicMiniTickersV3Api.proto\032 PublicBoo" +
      "kTickerBatchV3Api.proto\032$PublicIncreaseD" +
      "epthsBatchV3Api.proto\032\034PublicAggreDepths" +
      "V3Api.proto\032\033PublicAggreDealsV3Api.proto" +
      "\032 PublicAggreBookTickerV3Api.proto\"\360\007\n\024P" +
      "ushDataV3ApiWrapper\022\017\n\007channel\030\001 \001(\t\022)\n\013" +
      "publicDeals\030\255\002 \001(\0132\021.PublicDealsV3ApiH\000\022" +
      ";\n\024publicIncreaseDepths\030\256\002 \001(\0132\032.PublicI" +
      "ncreaseDepthsV3ApiH\000\0225\n\021publicLimitDepth" +
      "s\030\257\002 \001(\0132\027.PublicLimitDepthsV3ApiH\000\022-\n\rp" +
      "rivateOrders\030\260\002 \001(\0132\023.PrivateOrdersV3Api" +
      "H\000\0223\n\020publicBookTicker\030\261\002 \001(\0132\026.PublicBo" +
      "okTickerV3ApiH\000\022+\n\014privateDeals\030\262\002 \001(\0132\022" +
      ".PrivateDealsV3ApiH\000\022/\n\016privateAccount\030\263" +
      "\002 \001(\0132\024.PrivateAccountV3ApiH\000\0221\n\017publicS" +
      "potKline\030\264\002 \001(\0132\025.PublicSpotKlineV3ApiH\000" +
      "\0223\n\020publicMiniTicker\030\265\002 \001(\0132\026.PublicMini" +
      "TickerV3ApiH\000\0225\n\021publicMiniTickers\030\266\002 \001(" +
      "\0132\027.PublicMiniTickersV3ApiH\000\022=\n\025publicBo" +
      "okTickerBatch\030\267\002 \001(\0132\033.PublicBookTickerB" +
      "atchV3ApiH\000\022E\n\031publicIncreaseDepthsBatch" +
      "\030\270\002 \001(\0132\037.PublicIncreaseDepthsBatchV3Api" +
      "H\000\0225\n\021publicAggreDepths\030\271\002 \001(\0132\027.PublicA" +
      "ggreDepthsV3ApiH\000\0223\n\020publicAggreDeals\030\272\002" +
      " \001(\0132\026.PublicAggreDealsV3ApiH\000\022=\n\025public" +
      "AggreBookTicker\030\273\002 \001(\0132\033.PublicAggreBook" +
      "TickerV3ApiH\000\022\023\n\006symbol\030\003 \001(\tH\001\210\001\001\022\025\n\010sy" +
      "mbolId\030\004 \001(\tH\002\210\001\001\022\027\n\ncreateTime\030\005 \001(\003H\003\210" +
      "\001\001\022\025\n\010sendTime\030\006 \001(\003H\004\210\001\001B\006\n\004bodyB\t\n\007_sy" +
      "mbolB\013\n\t_symbolIdB\r\n\013_createTimeB\013\n\t_sen" +
      "dTimeB=\n\034com.mxc.push.common.protobufB\031P" +
      "ushDataV3ApiWrapperProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PublicDealsV3ApiProto.getDescriptor(),
          PublicIncreaseDepthsV3ApiProto.getDescriptor(),
          PublicLimitDepthsV3ApiProto.getDescriptor(),
          PrivateOrdersV3ApiProto.getDescriptor(),
          PublicBookTickerV3ApiProto.getDescriptor(),
          PrivateDealsV3ApiProto.getDescriptor(),
          PrivateAccountV3ApiProto.getDescriptor(),
          PublicSpotKlineV3ApiProto.getDescriptor(),
          PublicMiniTickerV3ApiProto.getDescriptor(),
          PublicMiniTickersV3ApiProto.getDescriptor(),
          PublicBookTickerBatchV3ApiProto.getDescriptor(),
          PublicIncreaseDepthsBatchV3ApiProto.getDescriptor(),
          PublicAggreDepthsV3ApiProto.getDescriptor(),
          PublicAggreDealsV3ApiProto.getDescriptor(),
          PublicAggreBookTickerV3ApiProto.getDescriptor(),
        });
    internal_static_PushDataV3ApiWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushDataV3ApiWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PushDataV3ApiWrapper_descriptor,
        new String[] { "Channel", "PublicDeals", "PublicIncreaseDepths", "PublicLimitDepths", "PrivateOrders", "PublicBookTicker", "PrivateDeals", "PrivateAccount", "PublicSpotKline", "PublicMiniTicker", "PublicMiniTickers", "PublicBookTickerBatch", "PublicIncreaseDepthsBatch", "PublicAggreDepths", "PublicAggreDeals", "PublicAggreBookTicker", "Symbol", "SymbolId", "CreateTime", "SendTime", "Body", });
    descriptor.resolveAllFeaturesImmutable();
    PublicDealsV3ApiProto.getDescriptor();
    PublicIncreaseDepthsV3ApiProto.getDescriptor();
    PublicLimitDepthsV3ApiProto.getDescriptor();
    PrivateOrdersV3ApiProto.getDescriptor();
    PublicBookTickerV3ApiProto.getDescriptor();
    PrivateDealsV3ApiProto.getDescriptor();
    PrivateAccountV3ApiProto.getDescriptor();
    PublicSpotKlineV3ApiProto.getDescriptor();
    PublicMiniTickerV3ApiProto.getDescriptor();
    PublicMiniTickersV3ApiProto.getDescriptor();
    PublicBookTickerBatchV3ApiProto.getDescriptor();
    PublicIncreaseDepthsBatchV3ApiProto.getDescriptor();
    PublicAggreDepthsV3ApiProto.getDescriptor();
    PublicAggreDealsV3ApiProto.getDescriptor();
    PublicAggreBookTickerV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
